---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /opt/bitnami/rabbitmq/var/lib/rabbitmq/

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: default 
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /tmp/

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv2
  namespace: default 
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /usr/

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongodb-pv3
#   namespace: default 
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: gp2
#   hostPath:
#     path: /opt/